[workspace]
authors = ["Yuiceee <931951301@qq.com>"]
channels = ["conda-forge", "bioconda"]
name = "open_deep_research"
platforms = ["linux-64"]
version = "0.1.0"

[pypi-options]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"


[tasks]

[dependencies]
python = "3.12.*"
pip = ">=25.1.1,<26"
seaborn = ">=0.13.2,<0.14"
numpy = "==2.2"
freesasa-c = ">=2.1.2,<3"
